version: "3.9"
services:
  web:
    build: ./gerobug_web
    ports:
      - "80:80"
    command: python manage.py runserver 0.0.0.0:80 --insecure
    environment:
      PYTHONUNBUFFERED: 1
    restart: unless-stopped
    depends_on:
      - dashboard

  dashboard:
    build: ./gerobug_dashboard
    ports:
      - "6320:6320"
    command: python manage.py runserver 0.0.0.0:6320 --insecure
    env_file:
      - ./gerobug_dashboard/secrets/gerobug_secret.env
    environment:
      PYTHONUNBUFFERED: 1
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    env_file:
      - ./gerobug_dashboard/secrets/db_secret.env
    environment:
      POSTGRES_DB: "gerobug_db"
      POSTGRES_USER: "gerobug"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./db_data/:/var/lib/postgresql/data/
    restart: unless-stopped