version: "3.9"
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static-content:/src/static
    depends_on:
      - web

  web:
    build: ./gerobug_web
    ports:
      - "8000:8000"
    #command: python manage.py runserver 0.0.0.0:80 --insecure
    command: gunicorn gerobug_web.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./gerobug_dashboard/secrets/db_secret.env
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - static-content:/src/static
    restart: unless-stopped
    depends_on:
      - dashboard

  dashboard:
    build: ./gerobug_dashboard
    ports:
      - "6320:6320"
    command: python manage.py runserver 0.0.0.0:6320 --insecure
    env_file:
      - ./gerobug_dashboard/secrets/gerobug_secret.env
      - ./gerobug_dashboard/secrets/db_secret.env
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - static-content:/src/static
      - ./log/:/src/log
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    command: postgres -c hba_file=/opt/gerobug_hba.conf
    env_file:
      - ./gerobug_dashboard/secrets/db_secret.env
    environment:
      POSTGRES_DB: "gerobug_db"
      POSTGRES_USER: "gerobug"
    volumes:
      - ./db_data/:/var/lib/postgresql/data/
      - ./gerobug_hba.conf:/opt/gerobug_hba.conf
    restart: unless-stopped
  
volumes:
  static-content: